In [1]:
import pandas as pd

df = pd.read_csv('sanfrancisco.csv')
df

,Unnamed: 0,Date,Max.TemperatureF,Mean.TemperatureF,Min.TemperatureF,Max.Dew.PointF,MeanDew.PointF,Min.DewpointF,Max.Humidity,Mean.Humidity,...,Min.VisibilityMiles,Max.Wind.SpeedMPH,Mean.Wind.SpeedMPH,Max.Gust.SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees.br...,city,season
0,1,1948-01-01,55,50.0,46.0,53.0,48.0,42.0,96.0,87.0,...,2.0,16.0,7.0,NaN,0.00,0.0,Fog-Rain,124<br />,San Francisco (CA),Winter
1,2,1948-01-02,57,55.0,53.0,56.0,53.0,51.0,93.0,91.0,...,3.0,22.0,11.0,NaN,0.00,0.0,Rain,202<br />,San Francisco (CA),Winter
2,3,1948-01-03,57,54.0,50.0,54.0,51.0,50.0,100.0,94.0,...,0.0,8.0,2.0,NaN,0.00,0.0,Fog,79<br />,San Francisco (CA),Winter
3,4,1948-01-04,59,57.0,55.0,55.0,54.0,54.0,97.0,91.0,...,3.0,18.0,7.0,NaN,0.00,0.0,Fog-Rain,191<br />,San Francisco (CA),Winter
4,5,1948-01-05,59,55.0,51.0,55.0,52.0,50.0,100.0,91.0,...,0.0,12.0,4.0,NaN,0.00,0.0,Fog,289<br />,San Francisco (CA),Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24738,24806,2015-12-27,48,41.0,34.0,37.0,34.0,29.0,82.0,71.0,...,9.0,15.0,4.0,17.0,0.01,5.0,Rain,156<br />,San Francisco (CA),Winter
24739,24807,2015-12-28,48,45.0,41.0,40.0,37.0,34.0,89.0,77.0,...,4.0,13.0,5.0,15.0,0.11,4.0,Rain,52<br />,San Francisco (CA),Winter
24740,24808,2015-12-29,54,45.0,36.0,41.0,36.0,28.0,92.0,67.0,...,10.0,12.0,3.0,13.0,0.00,1.0,NaN,250<br />,San Francisco (CA),Winter
24741,24809,2015-12-30,49,45.0,40.0,44.0,40.0,37.0,93.0,80.0,...,2.0,16.0,7.0,18.0,0.01,6.0,Rain,19<br />,San Francisco (CA),Winter
24742,24810,2015-12-31,51,45.0,39.0,37.0,34.0,28.0,85.0,66.0,...,10.0,17.0,8.0,20.0,0.00,1.0,NaN,78<br />,San Francisco (CA),Winter

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24743 entries, 0 to 24742
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0                 24743 non-null  int64
 1   Date                       24743 non-null  object
 2   Max.TemperatureF           24743 non-null  int64
 3   Mean.TemperatureF          24741 non-null  float64
 4   Min.TemperatureF           24742 non-null  float64
 5   Max.Dew.PointF             24742 non-null  float64
 6   MeanDew.PointF             24742 non-null  float64
 7   Min.DewpointF              24742 non-null  float64
 8   Max.Humidity               24742 non-null  float64
 9   Mean.Humidity              24742 non-null  float64
 10  Min.Humidity               24742 non-null  float64
 11  Max.Sea.Level.PressureIn   24742 non-null  float64
 12  Mean.Sea.Level.PressureIn  24742 non-null  float64
 13  Min.Sea.Level.PressureIn   24742 non-null  float64
 14  Max.VisibilityMiles        24741 non-null  float64
 15  Mean.VisibilityMiles       24741 non-null  float64
 16  Min.VisibilityMiles        24741 non-null  float64
 17  Max.Wind.SpeedMPH          24742 non-null  float64
 18  Mean.Wind.SpeedMPH         24742 non-null  float64
 19  Max.Gust.SpeedMPH          8504 non-null   float64
 20  PrecipitationIn            24743 non-null  object
 21  CloudCover                 22908 non-null  float64
 22  Events                     8095 non-null   object
 23  WindDirDegrees.br...       24743 non-null  object
 24  city                       24743 non-null  object
 25  season                     24743 non-null  object
dtypes: float64(18), int64(2), object(6)
memory usage: 4.9+ MB

In [3]:
df.describe()

,Unnamed: 0,Max.TemperatureF,Mean.TemperatureF,Min.TemperatureF,Max.Dew.PointF,MeanDew.PointF,Min.DewpointF,Max.Humidity,Mean.Humidity,Min.Humidity,Max.Sea.Level.PressureIn,Mean.Sea.Level.PressureIn,Min.Sea.Level.PressureIn,Max.VisibilityMiles,Mean.VisibilityMiles,Min.VisibilityMiles,Max.Wind.SpeedMPH,Mean.Wind.SpeedMPH,Max.Gust.SpeedMPH,CloudCover
count,24743.000000,24743.000000,24741.000000,24742.000000,24742.000000,24742.000000,24742.000000,24742.000000,24742.000000,24742.000000,24742.000000,24742.000000,24742.000000,24741.000000,24741.000000,24741.000000,24742.000000,24742.000000,8504.000000,22908.000000
mean,12405.428687,64.362082,57.152500,49.828268,51.242624,47.620443,43.808787,89.799531,74.406071,54.907202,30.090261,30.033948,29.977228,14.197365,10.681662,7.271008,20.432867,9.901059,29.228598,2.569801
std,7162.463166,8.647735,6.567785,5.846138,5.589795,6.219658,7.653558,7.628870,10.274828,14.251179,0.137716,0.136534,0.141723,4.286248,2.862666,3.563762,6.730061,4.359932,8.279627,2.677867
min,1.000000,0.000000,30.000000,25.000000,15.000000,10.000000,0.000000,36.000000,25.000000,7.000000,29.270000,29.030000,28.820000,1.000000,0.000000,0.000000,4.000000,0.000000,6.000000,0.000000
25%,6202.500000,58.000000,52.000000,46.000000,48.000000,44.000000,39.000000,86.000000,69.000000,47.000000,29.990000,29.940000,29.890000,10.000000,9.000000,5.000000,16.000000,7.000000,24.000000,0.000000
50%,12405.000000,64.000000,58.000000,51.000000,52.000000,49.000000,45.000000,90.000000,76.000000,56.000000,30.070000,30.020000,29.970000,15.000000,10.000000,8.000000,21.000000,10.000000,29.000000,2.000000
75%,18607.500000,70.000000,62.000000,54.000000,55.000000,52.000000,50.000000,96.000000,81.000000,64.000000,30.180000,30.120000,30.060000,20.000000,13.000000,10.000000,24.000000,13.000000,33.000000,5.000000
max,24810.000000,105.000000,85.000000,69.000000,67.000000,64.000000,62.000000,100.000000,100.000000,100.000000,30.780000,30.570000,30.510000,20.000000,20.000000,20.000000,132.000000,39.000000,204.000000,8.000000